#!/usr/bin/env bash
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.ub20-gpu.env}"

NON_INTERACTIVE=0
SKIP_PREFLIGHT=0

for arg in "$@"; do
  case "$arg" in
    --non-interactive)
      NON_INTERACTIVE=1
      ;;
    --skip-preflight)
      SKIP_PREFLIGHT=1
      ;;
    --env-file=*)
      ENV_FILE="${arg#*=}"
      ;;
    -h|--help)
      cat <<'EOF'
Usage: ./configure.sh [options]

Options:
  --non-interactive  Use defaults and do not ask questions.
  --skip-preflight   Do not run ./preflight.sh before configuration.
  --env-file=PATH    Write configuration to PATH. Default: ./.ub20-gpu.env
  -h, --help         Show this help.
EOF
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      exit 2
      ;;
  esac
done

if [[ -t 1 ]]; then
  BOLD="$(printf '\033[1m')"
  DIM="$(printf '\033[2m')"
  GREEN="$(printf '\033[32m')"
  YELLOW="$(printf '\033[33m')"
  RED="$(printf '\033[31m')"
  RESET="$(printf '\033[0m')"
else
  BOLD=""
  DIM=""
  GREEN=""
  YELLOW=""
  RED=""
  RESET=""
fi

info() {
  printf '%s\n' "${DIM}$1${RESET}"
}

ok() {
  printf '%s[OK]%s %s\n' "$GREEN" "$RESET" "$1"
}

warn() {
  printf '%s[WARN]%s %s\n' "$YELLOW" "$RESET" "$1"
}

fail() {
  printf '%s[FAIL]%s %s\n' "$RED" "$RESET" "$1"
}

ask_text() {
  local prompt="$1"
  local default="${2:-}"
  local answer

  if [[ "$NON_INTERACTIVE" -eq 1 || ! -t 0 ]]; then
    printf '%s' "$default"
    return
  fi

  read -r -p "$prompt [$default]: " answer
  printf '%s' "${answer:-$default}"
}

ask_yes_no() {
  local prompt="$1"
  local default="${2:-y}"
  local answer
  local suffix

  if [[ "$NON_INTERACTIVE" -eq 1 || ! -t 0 ]]; then
    [[ "$default" =~ ^[Yy]$ ]]
    return
  fi

  if [[ "$default" =~ ^[Yy]$ ]]; then
    suffix="Y/n"
  else
    suffix="y/N"
  fi

  while true; do
    read -r -p "$prompt [$suffix]: " answer
    answer="${answer:-$default}"
    case "$answer" in
      y|Y|yes|YES|Yes)
        return 0
        ;;
      n|N|no|NO|No)
        return 1
        ;;
      *)
        echo "Please answer yes or no."
        ;;
    esac
  done
}

shell_quote() {
  printf '%q' "$1"
}

normalize_bool() {
  if [[ "${1:-0}" == "1" || "${1:-}" == "true" || "${1:-}" == "yes" ]]; then
    printf '1'
  else
    printf '0'
  fi
}

run_preflight() {
  if [[ "$SKIP_PREFLIGHT" -eq 1 ]]; then
    warn "Preflight skipped."
    return 0
  fi

  if [[ ! -x "$SCRIPT_DIR/preflight.sh" ]]; then
    fail "Missing executable preflight.sh in $SCRIPT_DIR"
    return 1
  fi

  printf '%s\n' "${BOLD}Running preflight${RESET}"
  if "$SCRIPT_DIR/preflight.sh"; then
    ok "Preflight passed."
    return 0
  fi

  warn "Preflight reported blocking issues."
  if ask_yes_no "Continue writing container configuration anyway?" "n"; then
    return 0
  fi

  return 1
}

write_env() {
  local tmp_file
  tmp_file="$(mktemp)"

  {
    printf '# Generated by configure.sh. Safe to edit by hand.\n'
    printf 'PROJECT_DIR=%s\n' "$(shell_quote "$SCRIPT_DIR")"
    printf 'IMAGE_NAME=%s\n' "$(shell_quote "$IMAGE_NAME")"
    printf 'IMAGE_TAG=%s\n' "$(shell_quote "$IMAGE_TAG")"
    printf 'CONTAINER_NAME=%s\n' "$(shell_quote "$CONTAINER_NAME")"
    printf 'BASE_IMAGE=%s\n' "$(shell_quote "$BASE_IMAGE")"
    printf 'CONTAINER_USER=%s\n' "$(shell_quote "$CONTAINER_USER")"
    printf 'CONTAINER_SHELL=%s\n' "$(shell_quote "$CONTAINER_SHELL")"
    printf 'CONTAINER_WORKDIR=%s\n' "$(shell_quote "$CONTAINER_WORKDIR")"
    printf 'HOST_WORKDIR=%s\n' "$(shell_quote "$HOST_WORKDIR")"
    printf 'MOUNT_DATASET=%s\n' "$(normalize_bool "$MOUNT_DATASET")"
    printf 'HOST_DATASET_DIR=%s\n' "$(shell_quote "$HOST_DATASET_DIR")"
    printf 'CONTAINER_DATASET_DIR=%s\n' "$(shell_quote "$CONTAINER_DATASET_DIR")"
    printf 'SYNC_UID_GID=%s\n' "$(normalize_bool "$SYNC_UID_GID")"
    printf 'HOST_UID=%s\n' "$(shell_quote "$HOST_UID")"
    printf 'HOST_GID=%s\n' "$(shell_quote "$HOST_GID")"
    printf 'ENABLE_SUDO=1\n'
    printf 'PASSWORDLESS_SUDO=1\n'
    printf 'ENABLE_GPU=%s\n' "$(normalize_bool "$ENABLE_GPU")"
    printf 'NETWORK_HOST=1\n'
    printf 'SHM_SIZE=%s\n' "$(shell_quote "$SHM_SIZE")"
    printf 'BASE_APT_MIRROR=%s\n' "$(shell_quote "$BASE_APT_MIRROR")"
    printf 'INSTALL_MINICONDA=%s\n' "$(normalize_bool "$INSTALL_MINICONDA")"
    printf 'CONDA_DIR=%s\n' "$(shell_quote "$CONDA_DIR")"
    printf 'CONDA_AUTO_ACTIVATE_BASE=0\n'
    printf 'INSTALL_OH_MY_ZSH=%s\n' "$(normalize_bool "$INSTALL_OH_MY_ZSH")"
    printf 'ZSH_THEME=%s\n' "$(shell_quote "$ZSH_THEME")"
    printf 'ZSH_PLUGINS=%s\n' "$(shell_quote "$ZSH_PLUGINS")"
    printf 'COPY_ZSHRC=0\n'
    printf 'COPY_TMUX_CONF=%s\n' "$(normalize_bool "$COPY_TMUX_CONF")"
    printf 'VIM_CLIPBOARD=1\n'
    printf 'VIM_PACKAGE=%s\n' "$(shell_quote "$VIM_PACKAGE")"
    printf 'DEFAULT_PACKAGES=%s\n' "$(shell_quote "$DEFAULT_PACKAGES")"
  } > "$tmp_file"

  mv "$tmp_file" "$ENV_FILE"
}

main() {
  printf '%s\n' "${BOLD}ub20-gpu configuration${RESET}"
  info "Project directory: $SCRIPT_DIR"

  run_preflight || exit 1

  printf '\n%s\n' "${BOLD}Container basics${RESET}"
  IMAGE_NAME="$(ask_text "Image name" "ub20-gpu")"
  IMAGE_TAG="$(ask_text "Image tag" "latest")"
  CONTAINER_NAME="$(ask_text "Container name" "ub20-gpu")"
  BASE_IMAGE="$(ask_text "Base image" "ubuntu:20.04")"

  printf '\n%s\n' "${BOLD}User${RESET}"
  CONTAINER_USER="$(ask_text "Container user" "dev")"
  CONTAINER_SHELL="$(ask_text "Default shell" "zsh")"
  CONTAINER_WORKDIR="$(ask_text "Container workspace path" "/workspace")"
  HOST_WORKDIR="$(ask_text "Host workspace path to mount" "$PWD/workspace")"
  if ask_yes_no "Sync container UID/GID with current host user?" "y"; then
    SYNC_UID_GID=1
  else
    SYNC_UID_GID=0
  fi
  HOST_UID="$(id -u)"
  HOST_GID="$(id -g)"

  printf '\n%s\n' "${BOLD}Runtime${RESET}"
  if ask_yes_no "Enable GPU by default?" "y"; then
    ENABLE_GPU=1
  else
    ENABLE_GPU=0
  fi
  info "Host network is enabled by default."
  SHM_SIZE="$(ask_text "Docker --shm-size" "512m")"

  printf '\n%s\n' "${BOLD}Mounts${RESET}"
  if ask_yes_no "Mount a dataset directory?" "y"; then
    MOUNT_DATASET=1
    HOST_DATASET_DIR="$(ask_text "Host dataset directory" "$HOME/data")"
    CONTAINER_DATASET_DIR="$(ask_text "Container dataset directory" "/data")"
  else
    MOUNT_DATASET=0
    HOST_DATASET_DIR=""
    CONTAINER_DATASET_DIR="/data"
  fi

  printf '\n%s\n' "${BOLD}Packages${RESET}"
  BASE_APT_MIRROR="$(ask_text "APT mirror, keep 'official' unless you want a mirror" "official")"
  INSTALL_MINICONDA=1
  CONDA_DIR="$(ask_text "Miniconda install path" "/opt/conda")"
  INSTALL_OH_MY_ZSH=1
  ZSH_THEME="powerlevel10k/powerlevel10k"
  ZSH_PLUGINS="git vi-mode sudo z zsh-autosuggestions zsh-syntax-highlighting"
  COPY_TMUX_CONF=1
  VIM_PACKAGE="$(ask_text "Vim package for clipboard support" "vim-gtk3")"
  DEFAULT_PACKAGES="$(ask_text "APT packages" "git ${VIM_PACKAGE} curl wget cmake htop ripgrep tmux zsh sudo ca-certificates build-essential")"

  write_env
  ok "Configuration written to $ENV_FILE"
  info "Sudo, passwordless sudo, host network, tmux config copy, and Vim clipboard support are fixed on by this first version."
}

main "$@"
